name: fun_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter

  get: 4.3.8
  #网络
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1

  #UI界面
  #吐司
  oktoast: ^3.0.0
  #日志输出
  flutter_easylogger: ^2.3.3
  # webview控件 android webview ios WKWebView
  webview_flutter: ^2.0.13
  # 允许 Flutter 与原生 Web 视图通信的插件
  # flutter_webview_plugin: ^0.4.0
  # Html Encoder/Decoder
  html_unescape: ^2.0.0
  #转移html标签
  flutter_html: ^2.1.2
  #gif动画
  # flutter_gifimage: ^1.0.0
  #列表刷新
  flutter_easyrefresh: ^2.2.1
  # pull_to_refresh: ^2.0.0
  #骨架屏
  shimmer: ^2.0.0
  # pk_skeleton: ^0.0.2
  #滑动删除
  flutter_slidable: ^0.6.0
  #图片缓存框架
  cached_network_image: ^3.1.0
  #瀑布流
  flutter_staggered_grid_view: ^0.4.0
  #轮播图
  flutter_swiper_null_safety: ^1.0.2
  # 启动第三方app
  url_launcher: ^6.0.12
  #分享
  share: ^2.0.4
  #google play store ，apple app store 评分评价
  # launch_review: ^2.0.0
  #文件访问器
  open_file: ^3.2.1
  #路径访问
  path_provider: ^2.0.5
  # map存储
  localstorage: ^4.0.0+1
  # 键值对存储
  shared_preferences: ^2.0.8
  quiver: ^3.0.1
  #各种loading
  flutter_spinkit: ^5.1.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
